---
- name: Dockerのインストールに必要なパッケージをインストール
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: dockerリポジトリのGPGキーをシステムに追加
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: DockerリポジトリをAPTソースに追加
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: Dockerをインストール
  become: yes
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  notify: 
    - add_user_to_docker_group
    - restart_docker_daemon
  changed_when: yes

- meta: flush_handlers
...